### ISSUE TITLE
高级版的需要把app改成frontend才能使用？

### ISSUE THREAD

**Issue by xiaochengfu** [kaopur/yii2-doc-online#1]
抽空兼容一下高级版呗

**Comment by coder-liyang** [comment]
好的,最近工作有点忙,等有时间就兼容高级版

**Comment by artecfeng** [comment]
ApiDesc.php 79行添加个去除多个空格，否则带格式化的ide格式化后会有问题
$paramArr = explode(' ', trim(substr(preg_replace( "/\s(?=\s)/", "\\1", $comment ), $pos + 7)), 3);

**Comment by coder-liyang** [comment]
谢谢指正，今天晚上我会修复此问题。
